# Generated by Django 3.2.6 on 2022-01-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20220104_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date of publication'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
