# Generated by Django 3.2.6 on 2022-01-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_articles_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date_en',
            field=models.DateTimeField(null=True, verbose_name='Date of publication'),
        ),
        migrations.AddField(
            model_name='articles',
            name='date_ru',
            field=models.DateTimeField(null=True, verbose_name='Date of publication'),
        ),
        migrations.AddField(
            model_name='articles',
            name='full_text_en',
            field=models.TextField(null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='articles',
            name='full_text_ru',
            field=models.TextField(null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
    ]
